# LifestealPro

Settings:
  General:
    Prefix: "&8[&cLifesteal&4Pro&8]"
  Storage:
    # Available Types: flat
    StorageType: "flat"

Hearts:

  # What everyone starts with
  Starter: 10
  # What you get after being unbanned
  Unban: 5
  # The max amount you can accumulate
  Max: 100

  HeartLoss:
    # If enabled you lose heart of Death by Mob Entity
    mobsEnabled: true

  WorldSettings:
    Disabled-Worlds: ["world_the_end"]
    InstantEliminationWorlds: ["world_nether"]

Bans:
  Enabled: true
  BanCommand: "ban <user> Lifesteal Ban"
  UnbanCommand: "pardon <user>"

Messages:
  NoPermission: "&cNo permission."
  InvalidTarget: "&cIm sorry, but this user is invalid."
  InvalidUsage: "&cIm sorry, but this usage is invalid. View /help"
  InvalidProfile: "&cIm sorry, but this user does not have a data-profile yet. (they haven't joined)"

Messages-Admin:
  HelpPage:
    - "&8&m-------------------------------------------"
    - "&cLifestealPro by Xemu Development"
    - "&c/admin - Shows this page"
    - "&c/admin set <player> <hearts> - Sets hearts"
    - "&c/admin revive <player> - Revives a player & unbans"
    - "&8&m-------------------------------------------"
  FromSet: "<prefix> &7You set &e<player>'s &7hearts to: &a<hearts>" # Sender
  ToSet: "<prefix> &7Your hearts were set to: &a<hearts>" # Receiver
  Revive: "<prefix> &7You revived player and gave 5 hearts: &e<player>"

GUI:
  Hearts_Self:
    Title: "Hearts Overview - <target>"
    Item-DisplayName: "&cHearts: &f<hearts>"
    Item-Lore:
      - "You can steal hearts from others by murdering them."
